# Generated by Django 4.1.3 on 2022-11-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('transaction_method', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('customer_order_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('invoice_no', models.CharField(max_length=100)),
            ],
        ),
    ]
