# Generated by Django 4.1.7 on 2023-03-27 02:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarchentOrder',
            fields=[
                ('my_order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cu_name', models.CharField(max_length=50, null=True)),
                ('cu_mobile', models.CharField(max_length=20, null=True)),
                ('cu_email', models.EmailField(max_length=30, null=True)),
                ('cu_address', models.CharField(max_length=256, null=True)),
                ('cu_city', models.CharField(max_length=50, null=True)),
                ('cu_postcode', models.IntegerField(null=True)),
                ('sh_contact', models.CharField(max_length=20, null=True)),
                ('sh_address', models.CharField(max_length=256, null=True)),
                ('sh_city', models.CharField(max_length=30, null=True)),
                ('sh_country', models.CharField(max_length=30, null=True)),
                ('sh_phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'marchent_order',
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_url', models.URLField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('sp_order_id', models.CharField(max_length=100)),
                ('customer_order_id', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_city', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=30, null=True)),
                ('client_ip', models.GenericIPAddressField()),
                ('intent', models.CharField(max_length=10)),
                ('transactionStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedPayment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('disc_percent', models.IntegerField()),
                ('recived_amount', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('usd_amt', models.DecimalField(decimal_places=4, max_digits=10)),
                ('usd_rate', models.IntegerField()),
                ('card_holder_name', models.CharField(max_length=255, null=True)),
                ('card_number', models.CharField(max_length=255, null=True)),
                ('phone_no', models.CharField(max_length=255, null=True)),
                ('bank_trx_id', models.CharField(max_length=255, null=True)),
                ('invoice_no', models.CharField(max_length=255, null=True)),
                ('bank_status', models.CharField(max_length=255, null=True)),
                ('customer_order_id', models.CharField(max_length=255, null=True)),
                ('sp_code', models.CharField(max_length=10)),
                ('sp_massage', models.CharField(max_length=255)),
                ('sp_message', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('value1', models.CharField(max_length=255, null=True)),
                ('value2', models.CharField(max_length=255, null=True)),
                ('value3', models.CharField(max_length=255, null=True)),
                ('value4', models.CharField(max_length=255, null=True)),
                ('transaction_status', models.CharField(max_length=255, null=True)),
                ('method', models.CharField(max_length=255, null=True)),
                ('date_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_trxn_id', models.CharField(max_length=20)),
                ('tx_status', models.CharField(max_length=20)),
                ('bank_trnx_id', models.CharField(max_length=20, null=True)),
                ('bank_status', models.CharField(max_length=20, null=True)),
                ('tx_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tx_currency', models.CharField(max_length=15)),
                ('payment_channel', models.CharField(max_length=20, null=True)),
                ('tx_start_time', models.DateTimeField(auto_now_add=True)),
                ('sp_tx_time', models.DateTimeField(null=True)),
                ('tx_status_details', models.CharField(max_length=50, null=True)),
                ('receivable_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('my_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shurjopay.marchentorder')),
                ('tx_init_res', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shurjopay.paymentdetails')),
                ('tx_vrfy_res', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shurjopay.verifiedpayment')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
