# Generated by Django 4.1.7 on 2023-03-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shurjopay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='verifiedpayment',
            options={'managed': False},
        ),
    ]
