# Generated by Django 4.1.3 on 2022-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shurjopay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='card_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
