# Generated by Django 4.1.7 on 2023-03-22 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shurjopay', '0002_alter_orderhistory_card_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarchentTable',
            fields=[
                ('my_order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('cu_name', models.CharField(max_length=50, null=True)),
                ('cu_mobile', models.CharField(max_length=20, null=True)),
                ('cu_email', models.EmailField(max_length=30, null=True)),
                ('cu_address', models.CharField(max_length=256, null=True)),
                ('cu_city', models.CharField(max_length=50, null=True)),
                ('cu_postcode', models.IntegerField(null=True)),
                ('sh_contact', models.CharField(max_length=20, null=True)),
                ('sh_address', models.CharField(max_length=256, null=True)),
                ('sh_city', models.CharField(max_length=30, null=True)),
                ('sh_country', models.CharField(max_length=30, null=True)),
                ('sh_phone', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'marchent_table',
            },
        ),
        migrations.CreateModel(
            name='SPTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sp_trxn_id', models.CharField(max_length=20)),
                ('tx_status', models.CharField(max_length=20)),
                ('bank_trnx_id', models.CharField(max_length=20)),
                ('bank_status', models.CharField(max_length=20)),
                ('tx_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tx_currency', models.CharField(max_length=15)),
                ('payment_channel', models.CharField(max_length=20)),
                ('tx_start_time', models.DateTimeField()),
                ('sp_tx_time', models.DateTimeField()),
                ('tx_init_res', models.IntegerField()),
                ('tx_vrfy_res', models.IntegerField()),
                ('tx_status_details', models.CharField(max_length=50)),
                ('receivable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('my_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shurjopay.marchenttable')),
            ],
            options={
                'db_table': 'sp_transactions',
            },
        ),
    ]
