# Generated by Django 4.1.7 on 2023-03-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shurjopay', '0003_marchenttable_sptransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='prefix',
            field=models.UUIDField(),
        ),
    ]
