# Generated by Django 4.1.7 on 2023-03-22 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shurjopay', '0004_alter_orderhistory_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marchenttable',
            name='my_order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='prefix',
            field=models.CharField(max_length=10),
        ),
    ]
