# Generated by Django 4.1.7 on 2023-03-23 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shurjopay', '0005_alter_marchenttable_my_order_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarchentTable',
            new_name='MarchentOrder',
        ),
    ]
