# Generated by Django 4.1.7 on 2023-03-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shurjopay', '0007_paymentdetails_verifiedpayment_delete_orderhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='customer_email',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
